name: Firebase Config Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Inject Firebase Config from Secrets
      run: |
        echo "export const firebaseConfig = {" > src/config.js
        echo "  apiKey: '${{ secrets.API_KEY }}'," >> src/config.js
        echo "  authDomain: '${{ secrets.AUTH_DOMAIN }}'," >> src/config.js
        echo "  projectId: '${{ secrets.PROJECT_ID }}'," >> src/config.js
        echo "  storageBucket: '${{ secrets.STORAGE_BUCKET }}'," >> src/config.js
        echo "  messagingSenderId: '${{ secrets.MESSA_ID }}'," >> src/config.js
        echo "  appId: '${{ secrets.APP_ID }}'" >> src/config.js
        echo "};" >> src/config.js

    - name: Build the project
      run: npm run build

    - name: Deploy (optional step if needed)
      run: echo "Deployment steps go here"
